-- MySQL Script generated by MySQL Workbench
-- Fri May 13 18:22:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema myUw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myUw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myUw` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `myUw` ;

-- -----------------------------------------------------
-- Table `myUw`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`campus` (
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`building` (
  `abbreviation` VARCHAR(100) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `department` JSON NOT NULL,
  `campusName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`abbreviation`),
  INDEX `fromBuildingToCampus_idx` (`campusName` ASC) VISIBLE,
  CONSTRAINT `fromBuildingToCampus`
    FOREIGN KEY (`campusName`)
    REFERENCES `myUw`.`campus` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`schedule` (
  `id` INT NOT NULL,
  `registeredSchedule` VARCHAR(45) NOT NULL,
  `tips` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `prerequisite` VARCHAR(45) NOT NULL,
  `isInBookmark` TINYINT(1) NOT NULL,
  `genEduReq` VARCHAR(45) NOT NULL,
  `scheduleId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fromCourseToSchedule` (`scheduleId` ASC) VISIBLE,
  CONSTRAINT `fromCourseToSchedule`
    FOREIGN KEY (`scheduleId`)
    REFERENCES `myUw`.`schedule` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`program` (
  `name` VARCHAR(45) NOT NULL,
  `isInBookmark` TINYINT(1) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `departmentInfo` VARCHAR(45) NOT NULL,
  `isMajor` TINYINT(1) NOT NULL,
  `admissionType` JSON NOT NULL,
  `degreeRequirement` JSON NOT NULL,
  `campusName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fromProgramToCampus_idx` (`campusName` ASC) VISIBLE,
  CONSTRAINT `fromProgramToCampus`
    FOREIGN KEY (`campusName`)
    REFERENCES `myUw`.`campus` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`course-program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`course-program` (
  `courseId` INT NOT NULL,
  `programName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`courseId`, `programName`),
  INDEX `fromCourseProgramToProgram` (`programName` ASC) VISIBLE,
  CONSTRAINT `fromCourseProgramToCourse`
    FOREIGN KEY (`courseId`)
    REFERENCES `myUw`.`course` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fromCourseProgramToProgram`
    FOREIGN KEY (`programName`)
    REFERENCES `myUw`.`program` (`name`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`quarter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`quarter` (
  `title` VARCHAR(45) NOT NULL,
  `registrationPreview` VARCHAR(45) NOT NULL,
  `registeredCourses` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`title`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`section` (
  `sln` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `instructor` VARCHAR(45) NOT NULL,
  `additionalDetail` JSON NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `sectioncol5` VARCHAR(45) NOT NULL,
  `courseId` INT NOT NULL,
  `buildingAbbr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sln`),
  INDEX `fromSectionToCourse_idx` (`courseId` ASC) VISIBLE,
  INDEX `fromSectionToBuilding` (`buildingAbbr` ASC) VISIBLE,
  CONSTRAINT `fromSectionToBuilding`
    FOREIGN KEY (`buildingAbbr`)
    REFERENCES `myUw`.`building` (`abbreviation`),
  CONSTRAINT `fromSectionToCourse`
    FOREIGN KEY (`courseId`)
    REFERENCES `myUw`.`course` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`quarter-section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`quarter-section` (
  `quarterTitle` VARCHAR(45) NOT NULL,
  `sectionSln` INT NOT NULL,
  PRIMARY KEY (`quarterTitle`, `sectionSln`),
  INDEX `fromQuarterSectionToSection` (`sectionSln` ASC) VISIBLE,
  CONSTRAINT `fromQuarterSectionToQuarter`
    FOREIGN KEY (`quarterTitle`)
    REFERENCES `myUw`.`quarter` (`title`)
    ON DELETE CASCADE,
  CONSTRAINT `fromQuarterSectionToSection`
    FOREIGN KEY (`sectionSln`)
    REFERENCES `myUw`.`section` (`sln`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`student` (
  `netId` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `isShared` TINYINT NOT NULL,
  `campusName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`netId`),
  INDEX `fromStudentToCampus_idx` (`campusName` ASC) VISIBLE,
  CONSTRAINT `fromStudentToCampus`
    FOREIGN KEY (`campusName`)
    REFERENCES `myUw`.`campus` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myUw`.`student-course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myUw`.`student-course` (
  `studentNetId` INT NOT NULL,
  `courseId` INT NOT NULL,
  PRIMARY KEY (`studentNetId`, `courseId`),
  INDEX `fromStudentCourseToCourse_idx` (`courseId` ASC) VISIBLE,
  CONSTRAINT `fromStudentCourseToCourse`
    FOREIGN KEY (`courseId`)
    REFERENCES `myUw`.`course` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fromStudentCourseToStudent`
    FOREIGN KEY (`studentNetId`)
    REFERENCES `myUw`.`student` (`netId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
